#ifndef rapid_ext_arc_NrcClearanceSample_idl
#define rapid_ext_arc_NrcClearanceSample_idl

/*
 * Copyright (c) 2015 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"

module rapid {
  module ext {
    module arc {

      // signal_type values
      const octet SIGNAL_UNKNOWN              = 0;
      const octet SIGNAL_TRAFFIC_LIGHT_RED    = 1;
      const octet SIGNAL_TRAFFIC_LIGHT_YELLOW = 2;
      const octet SIGNAL_TRAFFIC_LIGHT_GREEN  = 3;
      const octet SIGNAL_STOP_SIGN            = 4;
      const octet SIGNAL_STOP_LINE            = 5;
      const octet SIGNAL_YIELD_SIGN           = 6;
      const octet SIGNAL_CROSSWALK            = 7;

      //@copy-c-declaration class NrcClearanceSampleTypeSupport;
      //@copy-c-declaration class NrcClearanceSampleDataWriter;
      //@copy-c-declaration class NrcClearanceSampleDataReader;
      //@copy-c-declaration struct NrcClearanceSampleSeq;

      //@copy-declaration /**
      //@copy-declaration  * NrcClearanceSample
      //@copy-declaration  */
      valuetype NrcClearanceSample : Message {

        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef NrcClearanceSampleTypeSupport TypeSupport;
        //@copy-c-declaration typedef NrcClearanceSampleDataWriter DataWriter;
        //@copy-c-declaration typedef NrcClearanceSampleDataReader DataReader;
        //@copy-c-declaration typedef NrcClearanceSampleSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef NrcClearanceSample Type;

        //@copy-c-declaration /** The type of the upcoming signal.
        //@copy-c-declaration   * It is unknown during a junction when the simulator (through ODR) cannot choose among overlapping lanes.
        //@copy-c-declaration   */
        public octet signal_type;

        //@copy-c-declaration /** clearance field is true when it is safe for the AV to go through the intersection */
        public boolean clearance;

        //@copy-c-declaration /** intersectionAhead is true when there is an intersection or crosswalk goal in the upcoming two goals within the mission plan */
        public boolean intersectionAhead;
      };
    };
  };
};

#endif // rapid_ext_arc_NrcClearanceSample_idl
