/*
 * Copyright (c) 2015 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"
#include "BaseTypes.idl"
#include "NrcMapLaneSetSample.idl"

module rapid {
  module ext {
    module arc {

      const octet NRC_STOP    = 0;
      const octet NRC_NO_STOP = 1;

      const octet NRC_ON_THIS_ROAD         = 0; // Remain on this road but drive in any lane.
      const octet NRC_STRICT_IN_THIS_LANE  = 1; // Remain in the specified line and allow only small deviation into other lanes. For example, to pass a parked car
      const octet NRC_RELAXED_IN_THIS_LANE = 2; // May move into other lanes briefly but return to this lane as soon a practical
      const octet NRC_COME_TO_THIS_POINT   = 3; 

      //@copy-declaration  /** 
      //@copy-declaration   * Direct copy of NRC ROS type.
      //@copy-declaration   * Provides the next position in-lane position that the vehicle will drive to. 
      //@copy-declaration   */
      struct DriveGoal {
        long lane_id;

        //@copy /** Note: known as variable s with the mission planner. */
        float longitudinal_position;

        Transform3D pose;

        //@copy /** The desired speed of the vehicle in the segment between the end of the prevoius drive goal and arriving at this goal */
        float approach_speed;

        //@copy /** Speed limit on road */
        float speed_limit;

        //@copy /** Departure Constraints */
        octet departure_constraints;

        //@copy /** Controls the freedom of the behavior recipient to change lanes etc. */
        octet drive_mode;
      };

      typedef sequence<DriveGoal,32> DriveGoalSequence;

      //@copy-c-declaration class  NrcDriveGoalWithLanesSampleTypeSupport;
      //@copy-c-declaration class  NrcDriveGoalWithLanesSampleDataWriter;
      //@copy-c-declaration class  NrcDriveGoalWithLanesSampleDataReader;
      //@copy-c-declaration struct NrcDriveGoalWithLanesSampleSeq;

      //@copy-declaration /**
      //@copy-declaration  * NrcDriveGoalWithLanesSample 
      //@copy-declaration  */
      valuetype NrcDriveGoalWithLanesSample : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSampleTypeSupport TypeSupport;
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSampleDataWriter DataWriter;
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSampleDataReader DataReader;
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSampleSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSample Type;
        public DriveGoalSequence drive_goals;
        public MapLaneSequence   map_lanes;
      };

    };
  };
};