/*
 * Copyright (c) 2015 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"
#include "BaseTypes.idl"
#include "NrcDriveGoalSample.idl"
#include "NrcMapLaneSetSample.idl"

module rapid {
  module ext {
    module arc {

      //@copy-c-declaration class  NrcDriveGoalWithLanesSampleTypeSupport;
      //@copy-c-declaration class  NrcDriveGoalWithLanesSampleDataWriter;
      //@copy-c-declaration class  NrcDriveGoalWithLanesSampleDataReader;
      //@copy-c-declaration struct NrcDriveGoalWithLanesSampleSeq;

      //@copy-declaration /**
      //@copy-declaration  * NrcDriveGoalWithLanesSample 
      //@copy-declaration  */
      valuetype NrcDriveGoalWithLanesSample : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSampleTypeSupport TypeSupport;
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSampleDataWriter DataWriter;
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSampleDataReader DataReader;
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSampleSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef NrcDriveGoalWithLanesSample Type;
        
        public DriveGoalSequence64 drive_goals;
        public MapLaneSequence8    map_lanes;
      };

    };
  };
};
