#ifndef rapid_ext_arc_NrcDriveGoalSample_idl
#define rapid_ext_arc_NrcDriveGoalSample_idl

/*
 * Copyright (c) 2015 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"

module rapid {
  module ext {
    module arc {
    
      // departure_constraints
      const octet NRC_STOP    = 0;
      const octet NRC_NO_STOP = 1;

      // drive_modes
      const octet NRC_ON_THIS_ROAD         = 0; // Remain on this road but drive in any lane.
      const octet NRC_STRICT_IN_THIS_LANE  = 1; // Remain in the specified line and allow only small deviation into other lanes. For example, to pass a parked car
      const octet NRC_RELAXED_IN_THIS_LANE = 2; // May move into other lanes briefly but return to this lane as soon a practical
      const octet NRC_COME_TO_THIS_POINT   = 3; 

      //@copy-declaration  /** 
      //@copy-declaration   * Direct copy of NRC ROS type.
      //@copy-declaration   * Provides the next position in-lane position that the vehicle will drive to. 
      //@copy-declaration   */
      struct DriveGoal {
        long lane_id;

        //@copy /** Note: known as variable s with the mission planner. */
        float longitudinal_position;

        Transform3D pose;

        //@copy /** The desired speed of the vehicle in the segment between the end of the prevoius drive goal and arriving at this goal */
        float approach_speed;

        //@copy /** Speed limit on road */
        float speed_limit;

        //@copy /** Departure Constraints */
        octet departure_constraints;

        //@copy /** Controls the freedom of the behavior recipient to change lanes etc. */
        octet drive_mode;
      };
      
      typedef sequence<DriveGoal,64> DriveGoalSequence64;

      //@copy-c-declaration class  NrcDriveGoalSampleTypeSupport;
      //@copy-c-declaration class  NrcDriveGoalSampleDataWriter;
      //@copy-c-declaration class  NrcDriveGoalSampleDataReader;
      //@copy-c-declaration struct NrcDriveGoalSampleSeq;
      //@copy-declaration /**
      //@copy-declaration  * NrcDriveGoalWithLanesSample 
      //@copy-declaration  */
      valuetype NrcDriveGoalSample : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef NrcDriveGoalSampleTypeSupport TypeSupport;
        //@copy-c-declaration typedef NrcDriveGoalSampleDataWriter DataWriter;
        //@copy-c-declaration typedef NrcDriveGoalSampleDataReader DataReader;
        //@copy-c-declaration typedef NrcDriveGoalSampleSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef NrcDriveGoalSample Type;
        public DriveGoalSequence64 drive_goals;
      };
    };
  };
};



#endif // rapid_ext_arc_NrcDriveGoalSample_idl
