#ifndef rapid_ext_arc_NrcImageRegions_idl
#define rapid_ext_arc_NrcImageRegions_idl

/*
 * Copyright (c) 2016 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"

module rapid {
  module ext {
    module arc {
    
      const String32 IMGROI_CLASS_FACE          = "face";
      const String32 IMGROI_CLASS_PEDESTRIAN    = "pedestrian";
      const String32 IMGROI_CLASS_ROAD_SIGN     = "road_sign";
      const String32 IMGROI_CLASS_STREET_SIGN   = "street_sign";
      const String32 IMGROI_CLASS_TRAFFIC_LIGHT = "traffic_light";
      const String32 IMGROI_CLASS_USER_DEFINED  = "user_defined";
    
      //@copy-declaration /** 
      //@copy-declaration  * Image region coordinates are given in range of 0..1 and 
      //@copy-declaration  * must be scaled by image size to obtain pixel coordinates. 
      //@copy-declaration  */ 
      struct ImageRegion {
        //@copy-declaration /** upper left corner of region, range 0..1 */
        Vec2f xy;
        //@copy-declaration /** size of region */
        Vec2f size; 
        //@copy-declaration /** unique identifier for region (tracking id) */
        long long regionId; 
        //@copy-declaration /** classification of region, e.g. pedestrian, sign, etc. */
        String32  classification;
        //@copy-declaration /** json encoded string containing additional meta data (optional) */
        String128 meta;
      };

      typedef sequence<ImageRegion,16>  ImageRegionSequence;

      //@copy-c-declaration class NrcImageRegionsTypeSupport;
      //@copy-c-declaration class NrcImageRegionsDataWriter;
      //@copy-c-declaration class NrcImageRegionsDataReader;
      //@copy-c-declaration struct NrcImageRegionsSeq;

      //@copy-declaration /**
      //@copy-declaration  * NrcImageRegions 
      //@copy-declaration  */
      valuetype NrcImageRegions : Message {

        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef NrcImageRegionsTypeSupport TypeSupport;
        //@copy-c-declaration typedef NrcImageRegionsDataWriter DataWriter;
        //@copy-c-declaration typedef NrcImageRegionsDataReader DataReader;
        //@copy-c-declaration typedef NrcImageRegionsSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef NrcImageRegions Type;

        /** identifier of camera stream that these image regions are associated with */
        public String64     cameraId;
        /** regions of interest */
        public ImageRegionSequence rois;
      };
    };
  };
};

#endif // rapid_ext_arc_NrcImageRegions_idl
