#ifndef rapid_ext_arc_NrcLanePlannerStateSample_idl
#define rapid_ext_arc_NrcLanePlannerStateSample_idl

/*
 * Copyright (c) 2015 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"

module rapid {
  module ext {
    module arc {

      /** planner_state values from LanePlannerState.msg */
      const octet NRC_PLANNER_IDLE            = 0;
      const octet NRC_PLANNER_ACTIVE          = 1;
      const octet NRC_PLANNER_SUBSTITUE_ROUTE = 2;
      const octet NRC_PLANNER_LOST            = 4;
      const octet NRC_PLANNER_BLOCKED         = 8;
      const octet NRC_PLANNER_PREEMPTED       = 16;
      const octet NRC_PLANNER_NO_CONTROL      = 32;

      //@copy-c-declaration class NrcLanePlannerStateSampleTypeSupport;
      //@copy-c-declaration class NrcLanePlannerStateSampleDataWriter;
      //@copy-c-declaration class NrcLanePlannerStateSampleDataReader;
      //@copy-c-declaration struct NrcLanePlannerStateSampleSeq;

      //@copy-declaration /**
      //@copy-declaration  * NrcLanePlannerStateSample 
      //@copy-declaration  */
      valuetype NrcLanePlannerStateSample : Message {

        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef NrcLanePlannerStateSampleTypeSupport TypeSupport;
        //@copy-c-declaration typedef NrcLanePlannerStateSampleDataWriter DataWriter;
        //@copy-c-declaration typedef NrcLanePlannerStateSampleDataReader DataReader;
        //@copy-c-declaration typedef NrcLanePlannerStateSampleSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef NrcLanePlannerStateSample Type;

        public octet status;

        public String32 status_message;

        public octet planner_state;

        // todo:
        //public MapLanePose vehicle_pose;
        //public DriveGoal[] planning_horizon_goals;
      };
    };
  };
};

#endif // rapid_ext_arc_NrcLanePlannerStateSample_idl
