#ifndef rapid_ext_arc_NrcMapAnnotationsUpdate_idl
#define rapid_ext_arc_NrcMapAnnotationsUpdate_idl

#include "Message.idl"

module rapid {
  module ext {
    module arc {

      //@copy-c-declaration class NrcMapAnnotationsUpdateTypeSupport;
      //@copy-c-declaration class NrcMapAnnotationsUpdateDataWriter;
      //@copy-c-declaration class NrcMapAnnotationsUpdateDataReader;
      //@copy-c-declaration struct NrcMapAnnotationsUpdateSeq;

      //@copy-declaration /**
      //@copy-declaration  * NrcMapAnnotationsUpdate
      //@copy-declaration  */
      valuetype NrcMapAnnotationsUpdate : Message {

        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef NrcMapAnnotationsUpdateTypeSupport TypeSupport;
        //@copy-c-declaration typedef NrcMapAnnotationsUpdateDataWriter DataWriter;
        //@copy-c-declaration typedef NrcMapAnnotationsUpdateDataReader DataReader;
        //@copy-c-declaration typedef NrcMapAnnotationsUpdateSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef NrcMapAnnotationsUpdate Type;
        
          /** 
           * Unique id for situation. Updates to same situation will use same requestId 
           */
          public long     messageId;  //@key  
          /**
           * json encoded string with proposed solution (if any)
           */
          public String2K updatedAnnotationFile;
        };
    };
  };
};

#endif // rapid_ext_arc_NrcMapAnnotationsUpdate_idl
