/*
 * Copyright (c) 2015 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"
#include "BaseTypes.idl"

module rapid {
  module ext {
    module arc {

      //@copy-declaration  /** Direct copy of NRC ROS type */
      struct MapPoint {
        float x;
        float y;
        float z;
        float theta;

        // height at the end of vector
        float z_end;
        float length;

        // position at MapLine. Start is 0
        float s;

        // curvatures. If it's line, all curv_* is 0
        float curv_start;
        float curv_mid;
        float curv_end;
      };
      
      typedef sequence<MapPoint,512> MapPointSequence512;
      typedef sequence<Vec2d,64>     Vec2dSequence64;
      
      //@copy-declaration  /** Direct copy of NRC ROS type */
      struct MapLine {
        MapPointSequence512 map_points;
        String32           type;
        String32           road_mark_type;
      };
      
      //@copy-declaration  /** Direct copy of NRC ROS type */
      struct MapLane {
        long            id;
        MapLine         lane_center;
        MapLine         left_boundary;
        MapLine         right_boundary;
        MapLine         left_outer_boundary;
        MapLine         right_outer_boundary;
        
        long            left_sibling_id;
        long            right_sibling_id;

        // "s" : distance along path from 1st point.
        DoubleSequence64 stop_line_positions;

        // "s", max speed [m/s]
        Vec2dSequence64 speed_along_path;

        // "s" value to start transition to next lane
        // -1 means no transition
        double transit_s;
      };
      
      typedef sequence<MapLane,8> MapLaneSequence8;
      
      //@copy-c-declaration class NrcMapLaneSetSampleTypeSupport;
      //@copy-c-declaration class NrcMapLaneSetSampleDataWriter;
      //@copy-c-declaration class NrcMapLaneSetSampleDataReader;
      //@copy-c-declaration struct NrcMapLaneSetSampleSeq;

      //@copy-declaration /**
      //@copy-declaration  * NrcMapLaneSetSample 
      //@copy-declaration  */
      valuetype NrcMapLaneSetSample : Message {
      
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef NrcMapLaneSetSampleTypeSupport TypeSupport;
        //@copy-c-declaration typedef NrcMapLaneSetSampleDataWriter DataWriter;
        //@copy-c-declaration typedef NrcMapLaneSetSampleDataReader DataReader;
        //@copy-c-declaration typedef NrcMapLaneSetSampleSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef NrcMapLaneSetSample Type;
        
        public MapLaneSequence8 map_lanes;
      };
    
    };
  };
};

