
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl rapidExtTraclabsIo
// ------------------------------
#ifndef RAPIDEXTTRACLABSIO_EXPORT_H
#define RAPIDEXTTRACLABSIO_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (RAPIDEXTTRACLABSIO_HAS_DLL)
#  define RAPIDEXTTRACLABSIO_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && RAPIDEXTTRACLABSIO_HAS_DLL */

#if !defined (RAPIDEXTTRACLABSIO_HAS_DLL)
#  define RAPIDEXTTRACLABSIO_HAS_DLL 1
#endif /* ! RAPIDEXTTRACLABSIO_HAS_DLL */

#if defined (RAPIDEXTTRACLABSIO_HAS_DLL) && (RAPIDEXTTRACLABSIO_HAS_DLL == 1)
#  if defined (RAPIDEXTTRACLABSIO_BUILD_DLL)
#    define rapidExtTraclabsIo_Export ACE_Proper_Export_Flag
#    define RAPIDEXTTRACLABSIO_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define RAPIDEXTTRACLABSIO_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* RAPIDEXTTRACLABSIO_BUILD_DLL */
#    define rapidExtTraclabsIo_Export ACE_Proper_Import_Flag
#    define RAPIDEXTTRACLABSIO_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define RAPIDEXTTRACLABSIO_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* RAPIDEXTTRACLABSIO_BUILD_DLL */
#else /* RAPIDEXTTRACLABSIO_HAS_DLL == 1 */
#  define rapidExtTraclabsIo_Export
#  define RAPIDEXTTRACLABSIO_SINGLETON_DECLARATION(T)
#  define RAPIDEXTTRACLABSIO_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* RAPIDEXTTRACLABSIO_HAS_DLL == 1 */

// Set RAPIDEXTTRACLABSIO_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (RAPIDEXTTRACLABSIO_NTRACE)
#  if (ACE_NTRACE == 1)
#    define RAPIDEXTTRACLABSIO_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define RAPIDEXTTRACLABSIO_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !RAPIDEXTTRACLABSIO_NTRACE */

#if (RAPIDEXTTRACLABSIO_NTRACE == 1)
#  define RAPIDEXTTRACLABSIO_TRACE(X)
#else /* (RAPIDEXTTRACLABSIO_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define RAPIDEXTTRACLABSIO_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (RAPIDEXTTRACLABSIO_NTRACE == 1) */

#endif /* RAPIDEXTTRACLABSIO_EXPORT_H */

// End of auto generated file.
